Inicializa projeto
codecon-dev/codecon-api pull request #8
Opened 2024-10-22 16:49 UTC by Markkop

- Init Nest
- Add docker
- Add instructions
- Create sample attendee database retrival

2024-10-22 18:00 UTC, brunofuentes reviewed
Mark, dei uma olhada no código e fiz alguns comentários. Nada de grave, apenas sugestões. Valeu.

2024-10-22 18:00 UTC, brunofuentes commented on docker-compose.yml
> +    image: postgres:13
sugiro usarmos postgres:16

2024-10-22 18:00 UTC, brunofuentes commented on Dockerfile
> +WORKDIR /usr/src/app
geralment eu uso o padrão ```WORKDIR /app``` apenas. Mas (acho) que não tem diferença...

2024-10-22 18:00 UTC, brunofuentes commented on Dockerfile
> +CMD ["npm", "run", "start:prod"]
sugestão: como último comando do Dockerfile, acho legal adicionar script externo por exemplo ``` RUN docker-entrypoint.sh```.

No script sh podemos colocar:
- rodar migrations (para garantir que todo mundo terá o mesmo estado da DB) !important
- rodar algum script de "seed" do database (caso houver no futuro)
- ...
- último comando do sh seria daí levantar o servidor, ```exec npm run start:prod``` por exemplo

2024-10-22 18:00 UTC, brunofuentes commented on .prettierrc
> +}
sugestão:

add "printWidth": 80,

2024-10-22 18:08 UTC, Markkop commented on docker-compose.yml
> +    image: postgres:13
Boa. Percebi que IA sugeriu um monte de version antiga das coisas no package.json tbm, podemos revisar isso junto

2024-10-22 18:23 UTC, erickcestari commented on package.json
Atualizar licença para MPL-2.0

2024-10-22 18:49 UTC, erickcestari commented on Dockerfile
> +RUN npm install
No projeto está sendo usado o pnpm para instalar as dependências e gerando o arquivo "pnpm-lock.yaml". Ao rodar o `npm install` pode ser que instale um pacote mais atualizado e causar falhas na aplicação, por isso o ideal seria instalarmos o pnpm e fazer os downloads das dependências usando o `pnpm install --frozen-lockfile` e incluir o `pnpm-lock.yaml` no Dockerfile.

2024-10-22 18:59 UTC, erickcestari commented on README.md
> +   git clone [repository-url]
Preencher o respository-url por https://github.com/codecon-dev/codecon-api.git

2024-10-22 18:59 UTC, erickcestari commented on README.md
> +This project is licensed under the [MIT License](LICENSE).
O projeto está licenciado pela MPL-2.0 license

2024-10-22 19:01 UTC, erickcestari commented
O README.md será em inglês?

2024-10-22 21:52 UTC, markkop-halborn commented
O Readme por enquanto é mais um placeholder gerado por IA

2024-10-22 22:00 UTC, Markkop commented on Dockerfile
> +WORKDIR /usr/src/app
Boa, não sabia desse padrão

2024-10-22 22:02 UTC, Markkop commented
Obrigado pelas reviews <3 Se quiserem/puderem revisar novamente

2024-10-22 23:38 UTC, Markkop commented
eu preciso 2 approves btw

2024-10-22 23:43 UTC, erickcestari approved these changes

2024-10-23 10:29 UTC, brunofuentes requested changes
precisa mudar uma coisinha ali no Dockerfile

2024-10-23 17:04 UTC, gabrnunes approved these changes

2024-10-23 17:35 UTC, brunofuentes approved these changes
vamo pra frente

2024-10-23 17:47 UTC, merged